name: user-thing
version: 0.1.0.0
github: "mkalvas/user-thing"
license: BSD3
author: "Mike Kalvas"
maintainer: "mkalvas@gmail.com"
copyright: "2022 Mike Kalvas"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/user-thing#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - Decimal >= 0.5.2
  - fixplate
  - mtl
  - random >= 1.2.1.1
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  user-thing-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - user-thing

tests:
  user-thing-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - user-thing
